//
//  Logos.swift
//  isErVoetbalVanavond?
//
//  Created by Tell van den Bergh on 08/01/2019.
//  Copyright © 2019 Tell van den Bergh. All rights reserved.
//

import Foundation

class Logos {
    
    let logoDict = [
        "FC Emmen" : "300px-FC_Emmen_logo",
        "Arsenal" : "580b57fcd9996e24bc43c4df",
        "Chelsea" : "580b57fcd9996e24bc43c4e1",
        "VVV Venlo" : "666px-VVV-Venlo_logo",
        "Helmond Sport" : "1200px-Helmond_Sport_logo",
        "1860 München" : "1860 munchen",
        "AC Milan" : "AC Milan",
        "ADO Den Haag" : "ADO-Den-Haag",
        "AEK Athens" : "AEK-Athens",
        "Afghanistan" : "Afghanistan",
        "Afghanistan Vrouwen" : "Afghanistan",
        "AJ Auxerre" : "AJ-Auxerre",
        "Ajax" : "Ajax",
        "Alaves" : "Alaves",
        "Albanië" : "Albanië",
        "Albanië Vrouwen" : "Albanië",
        "Almere City" : "Almere_City_FC_logo",
        "Altetic Bilbao" : "Altetic Bilbao",
        "Anderlecht" : "Anderlecht",
        "Andorra" : "Andorra",
        "Andorra Vrouwen" : "Andorra",
        "Antwerp" : "Antwerp",
        "APOEL Nicosia" : "APOEL-Nicosia",
        "Argentinië" : "Argentinië",
        "Argentinië Vrouwen" : "Argentinië",
        "Arminia Bielefeld" : "Arminia Bielefeld",
        "AS Monaco" : "AS-Monaco",
        "AS Roma" : "AS-Roma",
        "Aston Villa" : "Aston-Villa",
        "Atalanta" : "Atalanta",
        "Athletic Bilbao" : "Athletic-Bilbao",
        "Atlanta United" : "Atlanta United",
        "Atletico Madrid" : "Atletico",
        "Austin FC" : "Austin FC",
        "Australië" : "Australië",
        "Australië Vrouwen" : "Australië",
        "AZ" : "AZ",
        "Azerbeidzjan" : "Azerbeidzjan",
        "Azerbeidzjan Vrouwen" : "Azerbeidzjan",
        "Bahrein" : "Bahrein",
        "Bahrein Vrouwen" : "Bahrein",
        "Bayer Leverkusen" : "Bayer-Leverkusen",
        "Bayern Munchen" : "Bayern",
        "België" : "België",
        "België Vrouwen" : "België",
        "Benfica" : "Benfica",
        "Besiktas" : "Besiktas",
        "Real Betis" : "Betis",
        "Birmingham City" : "Birmingham City",
        "Blackburn Rovers" : "Blackburn-Rovers",
        "Bolivia" : "Bolivia",
        "Bolivia Vrouwen" : "Bolivia",
        "Bolton Wanderers" : "Bolton Wanderers",
        "Borussia Mönchengladbach" : "borussia",
        "Borussia Dortmund" : "Borussia-Dortmund",
        "Brazilië" : "Brazilië",
        "Brazilië Vrouwen" : "Brazilië",
        "Brentford" : "Brentford",
        "Brighton & Hove Albion" : "Brighton_&_Hove_Albion",
        "Bristol City" : "Bristol City",
        "Bulgarije" : "Bulgarije",
        "Bulgarije Vrouwen" : "Bulgarije",
        "Burkina Faso" : "Burkina faso",
        "Burkina Faso Vrouwen" : "Burkina faso",
        "Burnley FC" : "Burnley-FC",
        "Bursaspor" : "Bursaspor",
        "Cagliari" : "Cagliari",
        "Canada" : "Canada",
        "Canada Vrouwen" : "Canada",
        "Cardiff City" : "Cardiff City",
        "Celta de Vigo" : "Celta-de-Vigo",
        "Celtic" : "Celtic",
        "Cercle Brugge K.S.V." : "Cercle Brugge K.S.V.",
        "Chicago Fire" : "Chicago Fire",
        "Chievo Verona" : "Chievo-Verona",
        "Chili" : "Chili",
        "Chili Vrouwen" : "Chili",
        "China" : "China",
        "China Vrouwen" : "China",
        "Club Brugge" : "Club-Brugge",
        "Colombia" : "Colombia",
        "Colombia Vrouwen" : "Colombia",
        "Colorado Rapids" : "Colorado Rapids",
        "Columbus Crew SC" : "Columbus Crew SC",
        "Costa Rica" : "Costa Rica",
        "Costa Rica Vrouwen" : "Costa Rica",
        "Crystal Palace" : "Crystal Palace",
        "CSKA Moscow" : "CSKA-Moscow",
        "Cuba" : "Cuba",
        "Cuba Vrouwen" : "Cuba",
        "Cyprus" : "Cyprus",
        "Cyprus Vrouwen" : "Cyprus",
        "Czech Republic" : "Czech-Republic",
        "Czech Republic Vrouwen" : "Czech-Republic",
        "D.C. United" : "D.C. United",
        "Darmstadt 98" : "Darmstadt 98",
        "De Graafschap" : "De_Graafschap_Doetinchem",
        "Denemarken" : "Denemarken",
        "Denemarken Vrouwen" : "Denemarken",
        "Derby County" : "Derby-County",
        "Dinamo Kiev" : "Dinamo-Kiev",
        "Dinamo Zagreb" : "Dinamo-Zagreb",
        "Dnepr Dnepropetrovsk" : "Dnepr-Dnepropetrovsk",
        "Dnipro Dnipropetrovsk" : "Dnipro-Dnipropetrovsk",
        "Duitsland" : "Duitsland",
        "Duitsland Vrouwen" : "Duitsland",
        "Dynamo Dresden" : "Dynamo Dresden",
        "Ecuador" : "Ecuador",
        "Ecuador Vrouwen" : "Ecuador",
        "Egypte" : "Egypte",
        "Egypte Vrouwen" : "Egypte",
        "Eibar" : "Eibar",
        "Eintracht Frankfurt" : "Eintracht-Frankfurt",
        "EK" : "EK",
        "Empoli FC" : "Empoli FC",
        "Engeland" : "Engeland",
        "Engeland Vrouwen" : "Engeland",
        "Erzgebirge Aue" : "Erzgebirge Aue",
        "Espanyol" : "Espanyol",
        "Estland" : "Estland",
        "Estland Vrouwen" : "Estland",
        "Ethiopië" : "Ethiopië",
        "Ethiopië Vrouwen" : "Ethiopië",
        "Everton" : "Everton",
        "FC Cincinnati" : "FC Cincinnati",
        "FC Dallas" : "FC Dallas",
        "FC Ingolstadt" : "FC Ingolstadt",
        "FC Köln" : "FC Köln",
        "FC Sankt Pauli" : "FC Sankt Pauli",
        "FC Dordrecht" : "FC_Dordrecht",
        "FC Eindhoven" : "FC_Eindhoven_logo",
        "FC Volendam" : "FC_Volendam_logo",
        "FC Augsburg" : "FC-Augsburg",
        "FC Barcelona" : "FC-Barcelona",
        "FC Groningen" : "FC-Groningen",
        "FC Midtjylland" : "FC-Midtjylland",
        "FC Porto" : "FC-Porto",
        "FC Twente" : "FC-Twente-Enschede",
        "FC Utrecht" : "FC-Utrecht",
        "FC Kopenhagen" : "FCkopenhagen",
        "Fenerbahce" : "Fenerbahce",
        "Feyenoord" : "Feyenoord",
        "Finland" : "Finland",
        "Finland Vrouwen" : "Finland",
        "Fiorentina" : "Fiorentina",
        "Flamengo" : "Flamengo",
        "Fortuna Dusseldorf" : "Fortuna dusseldorf",
        "Fortuna Sittard" : "Fortuna-Sittard",
        "Frankrijk" : "Frankrijk",
        "Frankrijk Vrouwen" : "Frankrijk",
        "Freiburg" : "Freiburg",
        "Frosinone" : "Frosinone",
        "FSV Mainz" : "FSV-Mainz-5",
        "Fulham" : "Fulham-FC",
        "Galatasaray" : "Galatasaray",
        "Genoa" : "Genoa",
        "Georgië" : "Georgië",
        "Georgië Vrouwen" : "Georgië",
        "Getafe" : "Getafe",
        "Ghana" : "Ghana",
        "Ghana Vrouwen" : "Ghana",
        "Girona" : "Girona",
        "Glasgow Rangers" : "Glasgow-Rangers",
        "Go Ahead Eagles" : "Go-Ahead-Eagles",
        "Greuther Fürth" : "Greuther Fürth",
        "Griekenland" : "Griekenland",
        "Griekenland Vrouwen" : "Griekenland",
        "HSV" : "HSV",
        "Hannover 96" : "Hannover_96_Logo",
        "SC Heerenveen" : "Heerenveen",
        "Heidenheim" : "Heidenheim",
        "Heracles" : "Heracles-Almelo",
        "Hertha BSC" : "Hertha-BSC",
        "Hoffenheim" : "Hoffenheim",
        "Holstein Kiel" : "Holstein Kiel",
        "Hongarije" : "Hongarije",
        "Hongarije Vrouwen" : "Hongarije",
        "Houston Dynamo" : "Houston Dynamo",
        "Huddersfield Town" : "Huddersfield Town",
        "Huesca" : "Huesca",
        "Hull City" : "Hull-City",
        "Ierland" : "Ierland",
        "Ierland Vrouwen" : "Ierland",
        "Ijsland" : "Ijsland",
        "Ijsland Vrouwen" : "Ijsland",
        "India" : "India",
        "India Vrouwen" : "India",
        "Indonesië" : "Indonesië",
        "Indonesië Vrouwen" : "Indonesië",
        "Inter Miami" : "Inter Miami",
        "Internazionale" : "Internazionale",
        "Ipswich Town" : "Ipswich Town",
        "Irak" : "Irak",
        "Irak Vrouwen" : "Irak",
        "Iran" : "Iran",
        "Iran Vrouwen" : "Iran",
        "Israël" : "Israël",
        "Israël Vrouwen" : "Israël",
        "Italië" : "Italië",
        "Italië Vrouwen" : "Italië",
        "Ivoorkust" : "Ivoorkust",
        "Ivoorkust Vrouwen" : "Ivoorkust",
        "Jahn Regensburg" : "Jahn Regensburg",
        "Jamaica" : "Jamaica",
        "Jamaica Vrouwen" : "Jamaica",
        "Japan" : "Japan",
        "Japan Vrouwen" : "Japan",
        "Juventus" : "juventus-logo",
        "K.A.S. Eupen" : "K.A.S. Eupen",
        "K.S.C. Lokeren" : "K.S.C. Lokeren Oost-Vlaanderen",
        "K.V. Oostende" : "K.V. Oostende",
        "KAA Gent" : "KAA Gent",
        "Kameroen" : "Kameroen",
        "Kameroen Vrouwen" : "Kameroen",
        "Kasachstan" : "Kasachstan",
        "Kasachstan Vrouwen" : "Kasachstan",
        "Saint Etienne" : "kassiesa.net",
        "Kroatië" : "Kroatië",
        "Kroatië Vrouwen" : "Kroatië",
        "KV Kortrijk" : "KV Kortrijk",
        "LA Galaxy" : "LA Galaxy",
        "Lazio" : "Lazio",
        "Leeds United" : "Leeds United",
        "Leganes" : "leganes",
        "Legia Warsaw" : "Legia-Warsaw",
        "Leicester City" : "Leicester-City",
        "Letland" : "Letland",
        "Letland Vrouwen" : "Letland",
        "Levante" : "Levante-UD",
        "Lille" : "Lille-OSC",
        "Liverpool" : "Liverpool",
        "FC Den Bosch" : "Logo-FC-Den-Bosch",
        "Lokomotiv Moscow" : "Lokomotiv-Moscow",
        "Los Angeles FC" : "Los Angeles Football Club",
        "Luxenburg" : "Luxenburg",
        "Luxenburg Vrouwen" : "Luxenburg",
        "Maccabi Tel Aviv" : "Maccabi-Tel-Aviv",
        "Macedonië" : "Macedonië",
        "Magdeburg" : "Magdeburg",
        "Mainz" : "Mainz",
        "Malaga" : "Malaga",
        "Malmo" : "malmo",
        "Malmo FF" : "malmoff",
        "Manchester United" : "Manchester_United_FC_crest",
        "Manchester City" : "Manchester-City",
        "Marokko" : "Marokko",
        "Marokko Vrouwen" : "Marokko",
        "Mexico" : "Mexico",
        "Mexico Vrouwen" : "Mexico",
        "Middlesbrough" : "Middlesbrough",
        "Minnesota United" : "Minnesota United FC",
        "Moldavië" : "Moldavië",
        "Moldavië Vrouwen" : "Moldavië",
        "Montreal Impact" : "Montreal Impact",
        "MSV Duisburg" : "MSV Duisburg",
        "MVV" : "MVV_Maastricht_logo",
        "NAC" : "NAC",
        "Napoli" : "Napoli",
        "NEC-Nijmegen" : "NEC-Nijmegen",
        "Nederland" : "Nederland",
        "Nederland Vrouwen" : "Nederland",
        "New England Revolution" : "New England Revolution",
        "New York City FC" : "New York City FC",
        "New York Red Bulls" : "New York Red Bulls",
        "Newcastle United" : "newcastle",
        "Nieuw Zeeland" : "Nieuw Zeeland",
        "Nieuw Zeeland Vrouwen" : "Nieuw Zeeland",
        "Nigeria" : "Nigeria",
        "Nigeria Vrouwen" : "Nigeria",
        "noLogo" : "noLogo",
        "Noord Ierland" : "Noord Ireland",
        "Noord Korea" : "Noord Korea",
        "Noord Korea Vrouwen" : "Noord Korea",
        "Noorwegen" : "Noorwegen",
        "Noorwegen Vrouwen" : "Noorwegen",
        "Norwich City" : "Norwich-City",
        "Nottingham Forest" : "Nottingham-Forest",
        "Nürnberg" : "Nürnberg",
        "Oeganda" : "Oeganda",
        "Oeganda Vrouwen" : "Oeganda",
        "Oekraïne" : "Oekraïne",
        "Oekraïne Vrouwen" : "Oekraïne",
        "OGC Nice" : "OGC-Nice",
        "Olympiakos Piraeus" : "Olympiakos-Piraeus",
        "Olympique Lyon" : "Olympique-Lyon",
        "Olympique Marseille" : "Olympique-Marseille",
        "Oostenrijk" : "Oostenrijk",
        "Oostenrijk Vrouwen" : "Oostenrijk",
        "Orlando City" : "Orlando City SC",
        "Osasuna" : "Osasuna",
        "Paderborn" : "Paderborn",
        "Panama" : "Panama",
        "PAOK Thessaloniki" : "PAOK-Thessaloniki",
        "PSG" : "Paris-Saint-Germain",
        "Parma" : "Parma",
        "PEC Zwolle" : "PEC-Zwolle",
        "Peru" : "Peru",
        "Peru Vrouwen" : "Peru",
        "Philadelphia Union" : "Philadelphia Union",
        "Polen" : "Polen",
        "Polen Vrouwen" : "Polen",
        "Portland Timbers" : "Portland Timbers",
        "Portugal" : "Portugal",
        "Portugal Vrouwen" : "Portugal",
        "PSV" : "PSV-Eindhoven",
        "Qatar" : "Qatar",
        "Qatar Vrouwen" : "Qatar",
        "Queens Park Rangers" : "Queens-Park-Rangers",
        "R. Charleroi S.C." : "R. Charleroi S.C.",
        "Racing Club Genk" : "Racing Club Genk",
        "Racing-Genk" : "Racing-Genk",
        "Rayo Vallecano" : "Rayo-Vallecano",
        "RB Leipzig" : "RB-Leipzig",
        "Reading" : "Reading",
        "Real Salt Lake" : "Real Salt Lake",
        "Real Valladolid" : "Real Valladolid",
        "Real Madrid" : "Real-Madrid",
        "Real Sociedad" : "Real-Sociedad",
        "RKC Waalwijk" : "RKC",
        "Roda JC" : "Roda-JC-Kerkrade",
        "Roemenië" : "Roemenië",
        "Roemenië Vrouwen" : "Roemenië",
        "Rotherham United" : "Rotherham United",
        "Royal Excel Mouscron" : "Royal Excel Mouscron",
        "Rusland" : "Rusland",
        "Rusland Vrouwen" : "Rusland",
        "Sampdoria" : "Sampdoria",
        "San Jose Earthquakes" : "San Jose Earthquakes",
        "Sandhausen" : "Sandhausen",
        "Sassuolo" : "Sassuolo",
        "Saudi Arabie" : "Saudi Arabie",
        "Saudi Arabie Vrouwen" : "Saudi Arabie",
        "Excelsior" : "sbv-excelsior-logo-png-transparent-400",
        "SC Cambuur" : "SC_Cambuur_logo",
        "Telstar" : "SC_Telstar",
        "Schalke 04" : "Schalke-4",
        "Schotland" : "Schotland",
        "Schotland Vrouwen" : "Schotland",
        "Seattle Sounders FC" : "Seattle Sounders FC",
        "Senegal" : "Senegal",
        "Senegal Vrouwen" : "Senegal",
        "Servië" : "Servië",
        "Servië Vrouwen" : "Servië",
        "Sevilla" : "Sevilla",
        "Sheffield United" : "Sheffield United",
        "Sheffield Wednesday" : "Sheffield Wednesday",
        "Sint-Truidense V.V." : "Sint-Truidense V.V.",
        "Slavia Praag" : "Slavia Praag",
        "Slowakije" : "Slowakije",
        "Slowakije Vrouwen" : "Slowakije",
        "Southampton" : "Southampton-FC",
        "SPAL" : "SPAL",
        "Spanje" : "Spanje",
        "Spanje Vrouwen" : "Spanje",
        "Sparta Rotterdam" : "Sparta-Rotterdam",
        "Spartak Moscow" : "Spartak-Moscow",
        "Sporting Gijon" : "Sporting Gijon",
        "Sporting Kansas City" : "Sporting Kansas City",
        "Sporting Lissabon" : "Sporting-CP-Lisbon",
        "Standard Luik" : "standard liege",
        "Stoke City" : "Stoke-City",
        "Sunderland" : "Sunderland-AFC",
        "Swansea" : "Swansea-City",
        "Tottenham Hotspur" : "tettenham",
        "Top Oss" : "Top Oss",
        "Torino" : "Torino",
        "Toronto FC" : "Toronto FC",
        "Trabzonspor" : "Trabzonspor",
        "Tsjaad" : "Tsjaad",
        "Tsjaad Vrouwen" : "Tsjaad",
        "Tsjechië Vrouwen" : "Tsjechië",
        "Tunesië" : "Tunesië",
        "Tunesië Vrouwen" : "Tunesië",
        "Turkije" : "Turkije",
        "Turkije Vrouwen" : "Turkije",
        "UD Las Palmas" : "UD-Las-Palmas",
        "Udinese" : "Udinese",
        "Union Berlin" : "Union Berlin",
        "Uruguay" : "Uruguay",
        "Uruguay Vrouwen" : "Uruguay",
        "Valencia" : "Valencia",
        "Vancouver Whitecaps FC" : "Vancouver Whitecaps FC",
        "Venezuela" : "Venezuela",
        "Venezuela Vrouwen" : "Venezuela",
        "VfB Stuttgart" : "VfB-Stuttgart",
        "VfL Bochum" : "VfL Bochum",
        "VfL Wolfsburg" : "VfL-Wolfsburg",
        "Viktoria Plzen" : "Viktoria-Plzen",
        "Villarreal" : "Villarreal",
        "Vitesse" : "Vitesse-Arnhem",
        "VS" : "VS",
        "VS Vrouwen" : "VS",
        "Waasland Beveren" : "Waasland Beveren",
        "Wales" : "Wales",
        "Wales Vrouwen" : "Wales",
        "Watford" : "Watford-FC",
        "Werder Bremen" : "Werder-Bremen",
        "West Bromwich Albion" : "West-Bromwich-Albion",
        "West Ham United" : "westHam",
        "Wigan Athletic" : "Wigan-Athletic",
        "Willem II" : "Willem-II-Tilburg",
        "Wit Rusland" : "Wit Rusland",
        "Wolfsburg" : "Wolfsburg",
        "Wolverhampton Wanderers" : "Wolverhampton-Wanderers",
        "Yemen" : "Yemen",
        "Young Boys" : "Young-Boys",
        "Zenit St.Petersburg" : "Zenit-St.-Petersburg",
        "Zuid Afrika" : "Zuid Afrika",
        "Zuid Afrika Vrouwen" : "Zuid Afrika",
        "Zuid Korea" : "Zuid Korea",
        "Zuid Korea Vrouwen" : "Zuid Korea",
        "Zulte Waregem" : "Zulte Waregem",
        "Zweden" : "Zweden",
        "Zweden Vrouwen" : "Zweden",
        "Zwitserland" : "Zwitserland",
        "Zwitserland Vrouwen" : "Zwitserland",
        "FC Basel" : "FC-Basel"
    ]
}
